/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as dashboardRouteImport } from './routes/(dashboard)/route'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as dashboardIndexImport } from './routes/(dashboard)/index'
import { Route as SettingsRemoteStorageImport } from './routes/settings/remote-storage'
import { Route as SettingsLocalDataImport } from './routes/settings/local-data'
import { Route as SettingsGitConfigImport } from './routes/settings/git-config'
import { Route as dashboardNiftiViewerImport } from './routes/(dashboard)/nifti-viewer'
import { Route as dashboardDicomViewerImport } from './routes/(dashboard)/dicom-viewer'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const dashboardRouteRoute = dashboardRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardIndexRoute = dashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const SettingsRemoteStorageRoute = SettingsRemoteStorageImport.update({
  id: '/settings/remote-storage',
  path: '/settings/remote-storage',
  getParentRoute: () => rootRoute,
} as any)

const SettingsLocalDataRoute = SettingsLocalDataImport.update({
  id: '/settings/local-data',
  path: '/settings/local-data',
  getParentRoute: () => rootRoute,
} as any)

const SettingsGitConfigRoute = SettingsGitConfigImport.update({
  id: '/settings/git-config',
  path: '/settings/git-config',
  getParentRoute: () => rootRoute,
} as any)

const dashboardNiftiViewerRoute = dashboardNiftiViewerImport.update({
  id: '/nifti-viewer',
  path: '/nifti-viewer',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const dashboardDicomViewerRoute = dashboardDicomViewerImport.update({
  id: '/dicom-viewer',
  path: '/dicom-viewer',
  getParentRoute: () => dashboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/dicom-viewer': {
      id: '/(dashboard)/dicom-viewer'
      path: '/dicom-viewer'
      fullPath: '/dicom-viewer'
      preLoaderRoute: typeof dashboardDicomViewerImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(dashboard)/nifti-viewer': {
      id: '/(dashboard)/nifti-viewer'
      path: '/nifti-viewer'
      fullPath: '/nifti-viewer'
      preLoaderRoute: typeof dashboardNiftiViewerImport
      parentRoute: typeof dashboardRouteImport
    }
    '/settings/git-config': {
      id: '/settings/git-config'
      path: '/settings/git-config'
      fullPath: '/settings/git-config'
      preLoaderRoute: typeof SettingsGitConfigImport
      parentRoute: typeof rootRoute
    }
    '/settings/local-data': {
      id: '/settings/local-data'
      path: '/settings/local-data'
      fullPath: '/settings/local-data'
      preLoaderRoute: typeof SettingsLocalDataImport
      parentRoute: typeof rootRoute
    }
    '/settings/remote-storage': {
      id: '/settings/remote-storage'
      path: '/settings/remote-storage'
      fullPath: '/settings/remote-storage'
      preLoaderRoute: typeof SettingsRemoteStorageImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexImport
      parentRoute: typeof dashboardRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface dashboardRouteRouteChildren {
  dashboardDicomViewerRoute: typeof dashboardDicomViewerRoute
  dashboardNiftiViewerRoute: typeof dashboardNiftiViewerRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardDicomViewerRoute: dashboardDicomViewerRoute,
  dashboardNiftiViewerRoute: dashboardNiftiViewerRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dicom-viewer': typeof dashboardDicomViewerRoute
  '/nifti-viewer': typeof dashboardNiftiViewerRoute
  '/settings/git-config': typeof SettingsGitConfigRoute
  '/settings/local-data': typeof SettingsLocalDataRoute
  '/settings/remote-storage': typeof SettingsRemoteStorageRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/dicom-viewer': typeof dashboardDicomViewerRoute
  '/nifti-viewer': typeof dashboardNiftiViewerRoute
  '/settings/git-config': typeof SettingsGitConfigRoute
  '/settings/local-data': typeof SettingsLocalDataRoute
  '/settings/remote-storage': typeof SettingsRemoteStorageRoute
  '/': typeof dashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/(dashboard)/dicom-viewer': typeof dashboardDicomViewerRoute
  '/(dashboard)/nifti-viewer': typeof dashboardNiftiViewerRoute
  '/settings/git-config': typeof SettingsGitConfigRoute
  '/settings/local-data': typeof SettingsLocalDataRoute
  '/settings/remote-storage': typeof SettingsRemoteStorageRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dicom-viewer'
    | '/nifti-viewer'
    | '/settings/git-config'
    | '/settings/local-data'
    | '/settings/remote-storage'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/dicom-viewer'
    | '/nifti-viewer'
    | '/settings/git-config'
    | '/settings/local-data'
    | '/settings/remote-storage'
    | '/'
    | '/settings'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/onboarding'
    | '/(dashboard)/dicom-viewer'
    | '/(dashboard)/nifti-viewer'
    | '/settings/git-config'
    | '/settings/local-data'
    | '/settings/remote-storage'
    | '/(dashboard)/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SettingsGitConfigRoute: typeof SettingsGitConfigRoute
  SettingsLocalDataRoute: typeof SettingsLocalDataRoute
  SettingsRemoteStorageRoute: typeof SettingsRemoteStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SettingsGitConfigRoute: SettingsGitConfigRoute,
  SettingsLocalDataRoute: SettingsLocalDataRoute,
  SettingsRemoteStorageRoute: SettingsRemoteStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(dashboard)",
        "/onboarding",
        "/settings/git-config",
        "/settings/local-data",
        "/settings/remote-storage",
        "/settings/"
      ]
    },
    "/(dashboard)": {
      "filePath": "(dashboard)/route.tsx",
      "children": [
        "/(dashboard)/dicom-viewer",
        "/(dashboard)/nifti-viewer",
        "/(dashboard)/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/(dashboard)/dicom-viewer": {
      "filePath": "(dashboard)/dicom-viewer.tsx",
      "parent": "/(dashboard)"
    },
    "/(dashboard)/nifti-viewer": {
      "filePath": "(dashboard)/nifti-viewer.tsx",
      "parent": "/(dashboard)"
    },
    "/settings/git-config": {
      "filePath": "settings/git-config.tsx"
    },
    "/settings/local-data": {
      "filePath": "settings/local-data.tsx"
    },
    "/settings/remote-storage": {
      "filePath": "settings/remote-storage.tsx"
    },
    "/(dashboard)/": {
      "filePath": "(dashboard)/index.tsx",
      "parent": "/(dashboard)"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
